export default Object.freeze({
  PLAY: 'Play',
  TRAIN: 'Train',
  MAIN: 'Main',
  STATISTICS: 'Statistics',
  NOT_FOUND: '404 Not found',
  NOT_DIFFICULT_WORDS: 'There are no difficult words',
  START_GAME: 'Start game',
  CATEGORY: 'Category',
  WORD: 'Word',
  TRANSLATION: 'Translation',
  ERROR: 'Error',
  PERCENT: '%',
  DIFFICULT_WORDS: 'Difficult words',
  LOGIN: 'Login',
  CLOSE: 'close',
});
